---
- hosts: all
  become: true
  tasks:
    - name: Install apache packages
      apt:
       name: apache2
       state: present
    - name: start apache server
      service:
        name: apache2
        state: started
        enabled: true
    - name: deploy static website
      copy:
        src: index.html
        dest: /var/www/html
...
